title: Klevis Ndoka
description: Senior Software Engineer Team Lead & Product Owner at dev.al in Tirana, Albania. 10+ years building scalable solutions.
baseurl: ""
url: https://klevisndoka.github.io

# Theme
theme: jekyll-theme-basically-basic

# Skin (optional: basically-basic, solar, solar-dark, solar-light-solar, solar-light, etc.)
skin: basically-basic

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/

# Markdown processor
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Sass
sass:
  sourcemap: never
  style: compressed

# SEO
twitter:
  username: ClevisNdoka

# Social
author:
  name: KlevisNdoka
  twitter: ClevisNdoka

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X
